server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/restaurant}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    locale: en_US

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}
  secure: true

payment:
  vnpay:
    tmnCode: ${VNP_TMNCODE}
    secretKey: ${VNP_SECRETKEY}
